"""adding cascade

Revision ID: 2bf9da188a2b
Revises: cba6ab532a9c
Create Date: 2024-02-20 16:04:02.788499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf9da188a2b'
down_revision: Union[str, None] = 'cba6ab532a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_groups_user_id_fkey', 'user_groups', type_='foreignkey')
    op.drop_constraint('user_groups_group_id_fkey', 'user_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.create_foreign_key('user_groups_group_id_fkey', 'user_groups', 'groups', ['group_id'], ['id'])
    op.create_foreign_key('user_groups_user_id_fkey', 'user_groups', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
